# Generated by Django 3.1.1 on 2020-09-06 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=50)),
                ('semester', models.CharField(choices=[(1, 'First'), (2, 'Second'), (3, 'Third'), (4, 'Fourth'), (5, 'Fifth'), (6, 'Sixth'), (7, 'Seventh'), (8, 'Eighth')], max_length=20)),
                ('course', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[(1, 'Male'), (2, 'Female'), (3, 'Other'), (4, 'Preferred Not to Say')], max_length=20)),
                ('email', models.EmailField(max_length=150)),
                ('WNumber', models.CharField(max_length=10)),
            ],
        ),
    ]
