# Generated by Django 3.1.1 on 2020-09-06 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reguser',
            name='gender',
            field=models.CharField(choices=[(0, 'Male'), (1, 'Female'), (2, 'Other'), (3, 'Preferred Not to Say')], max_length=20),
        ),
        migrations.AlterField(
            model_name='reguser',
            name='semester',
            field=models.CharField(choices=[(0, 'First'), (1, 'Second'), (2, 'Third'), (3, 'Fourth'), (4, 'Fifth'), (5, 'Sixth'), (6, 'Seventh'), (7, 'Eighth')], max_length=20),
        ),
    ]
