# Generated by Django 3.1.1 on 2020-09-06 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_auto_20200906_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reguser',
            name='gender',
            field=models.CharField(choices=[(1, 'Male'), (2, 'Female'), (3, 'Other'), (4, 'Preferred Not to Say')], max_length=20),
        ),
        migrations.AlterField(
            model_name='reguser',
            name='semester',
            field=models.CharField(choices=[(1, 'First'), (2, 'Second'), (3, 'Third'), (4, 'Fourth'), (5, 'Fifth'), (6, 'Sixth'), (7, 'Seventh'), (8, 'Eighth')], max_length=20),
        ),
    ]
